import type { RegisteredFunction } from "../function-registry";

/**
 * Given a flat list of registered functions, produce the content of
 * bbf/_generated/api.d.ts — the type-safe API object.
 */
export function generateApiTypes(fns: RegisteredFunction[]): string {
  // Group by path segments
  const groups: Record<string, Record<string, Record<string, RegisteredFunction>>> = {
    queries:   {},
    mutations: {},
    actions:   {},
  };

  for (const fn of fns) {
    const parts = fn.path.split("/");
    const kind  = parts[0];   // queries | mutations | actions
    const file  = parts.slice(1, -1).join("/") || "root";
    const name  = parts[parts.length - 1];

    if (!groups[kind]) continue;
    if (!groups[kind][file]) groups[kind][file] = {};
    groups[kind][file][name] = fn;
  }

  const lines: string[] = [
    `// AUTO-GENERATED by BetterBase IaC — DO NOT EDIT`,
    `// Source: bbf/**/*.ts`,
    `// Run \`bb iac generate\` to regenerate`,
    ``,
    `import type { QueryRegistration, MutationRegistration, ActionRegistration } from "@betterbase/core/iac";`,
    ``,
    `export declare const api: {`,
  ];

  for (const [kind, files] of Object.entries(groups)) {
    lines.push(`  ${kind}: {`);
    for (const [file, exports] of Object.entries(files)) {
      const key = file.replace(/\//g, "_") || "root";
      lines.push(`    ${key}: {`);
      for (const [name, fn] of Object.entries(exports)) {
        const type = fn.kind === "query"
          ? "QueryRegistration"
          : fn.kind === "mutation"
          ? "MutationRegistration"
          : "ActionRegistration";
        lines.push(`      ${name}: ${type}<any, any>;`);
      }
      lines.push(`    };`);
    }
    lines.push(`  };`);
  }

  lines.push(`};`);
  lines.push(``);

  // Also generate FunctionReference type for useQuery/useMutation
  lines.push(`export type FunctionReference<T extends "query" | "mutation" | "action"> =`);
  lines.push(`  T extends "query"    ? QueryRegistration<any, any>`);
  lines.push(`  : T extends "mutation" ? MutationRegistration<any, any>`);
  lines.push(`  : ActionRegistration<any, any>;`);

  return lines.join("\n");
}
