import type { SerializedSchema, SerializedTable, SerializedColumn } from "../schema-serializer";

function colTypeToSqlite(type: string, colName: string): string {
  if (type === "string" || type.startsWith("id:") || type.startsWith("literal:") || type.startsWith("union:"))
    return `text('${colName}')`;
  if (type === "number")  return `real('${colName}')`;
  if (type === "int64")   return `integer('${colName}')`;
  if (type === "boolean") return `integer('${colName}', { mode: 'boolean' })`;
  if (type === "date")    return `integer('${colName}', { mode: 'timestamp' })`;
  if (type.startsWith("array:") || type === "object") return `text('${colName}', { mode: 'json' })`;
  return `text('${colName}')`;
}

function colTypeToPostgres(type: string, colName: string): string {
  if (type === "string" || type.startsWith("id:") || type.startsWith("literal:") || type.startsWith("union:"))
    return `text('${colName}')`;
  if (type === "number")  return `doublePrecision('${colName}')`;
  if (type === "int64")   return `bigint('${colName}', { mode: 'bigint' })`;
  if (type === "boolean") return `boolean('${colName}')`;
  if (type === "date")    return `timestamp('${colName}', { withTimezone: true })`;
  if (type.startsWith("array:") || type === "object") return `jsonb('${colName}')`;
  return `text('${colName}')`;
}

function generateTableCode(table: SerializedTable, dialect: "sqlite" | "postgres"): string {
  const colFn  = dialect === "sqlite" ? colTypeToSqlite : colTypeToPostgres;
  const tableFn = dialect === "sqlite" ? "sqliteTable" : "pgTable";

  const cols = table.columns.map((col) => {
    let def = colFn(col.type, col.name);

    if (col.name === "_id") {
      def += ".primaryKey()";
    } else if (!col.optional && !col.system) {
      def += ".notNull()";
    }

    if (col.name === "_createdAt" || col.name === "_updatedAt") {
      def += ".default(sql`now()`)";
    }

    return `  ${col.name}: ${def}`;
  }).join(",\n");

  // Add index definitions as a third argument to the table fn
  const indexLines = table.indexes.map((idx) => {
    const fields = idx.fields.map((f) => `table.${f}`).join(", ");
    if (idx.type === "uniqueIndex") return `  ${idx.name}: uniqueIndex('${table.name}_${idx.name}').on(${fields})`;
    return `  ${idx.name}: index('${table.name}_${idx.name}').on(${fields})`;
  });

  const tableBody = indexLines.length
    ? `, (table) => ({\n${indexLines.join(",\n")}\n})`
    : "";

  return `export const ${table.name} = ${tableFn}('${table.name}', {\n${cols}\n}${tableBody});`;
}

export function generateDrizzleSchema(
  schema:  SerializedSchema,
  dialect: "sqlite" | "postgres" = "sqlite"
): string {
  const imports = dialect === "sqlite"
    ? `import { sqliteTable, text, real, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';\nimport { sql } from 'drizzle-orm';`
    : `import { pgTable, text, doublePrecision, bigint, boolean, timestamp, jsonb, index, uniqueIndex } from 'drizzle-orm/pg-core';\nimport { sql } from 'drizzle-orm';`;

  const header = `// AUTO-GENERATED by BetterBase IaC — DO NOT EDIT\n// Source: bbf/schema.ts\n// Generated: ${schema.generated}\n\n${imports}\n\n`;

  const tables = schema.tables.map((t) => generateTableCode(t, dialect)).join("\n\n");

  return header + tables + "\n";
}
